// angular-to-do-list/src/app/header/header.component.ts
import { Component, EventEmitter, OnInit, Output } from '@angular/core';

@Component({
  selector: 'app-header',
  templateUrl: './header.component.html',
  styleUrls: ['./header.component.css'],
})
export class HeaderComponent {
  constructor() {}

  @Output() toggleFooterEvt = new EventEmitter();

  toggleFooter() {
    this.toggleFooterEvt.emit();
  }
}

<div class="bgcolorgree jumbotron jumbotron-fluid">
  <div class="container row">
    <div class="col-md-8">
      <h1 class="display-4">TO DO LIST</h1>
    </div>
    <div class="col-md-4">
      <p>
        <button class="btn btn-primary" (click)="toggleFooter()">
          Toggle Footer
        </button>
      </p>
    </div>
  </div>
</div>

// angular-to-do-list/src/app/react-component/components/Header/index.tsx
import { css, cx } from '@emotion/css';
import * as React from 'react';

interface IHeaderProps {
  toggleFooter: () => void;
}

export const HeaderFC: React.FC<IHeaderProps> = ({ toggleFooter }) => {
  return (
    <div className={cx(styles.bgcolorgree, "jumbotron jumbotron-fluid")}>
      <div className='container row'>
        <div className='col-md-8'>
          <h1 className='display-4'>TO DO LIST</h1>
        </div>
        <div className='col-md-4'>
          <p>
            <button className='btn btn-primary' onClick={toggleFooter}>
              Toggle Footer
            </button>
          </p>
        </div>
      </div>
    </div>
  );
};

const styles = {
  header: css`
    width: 70%;
    padding: 3%;
    background-color: green;
  `,
  bgcolorgree: css`
    background-color: yellowgreen;
  `,
};
