// angular-to-do-list/src/app/to-do-list/to-do-list.component.ts
import {
  Component,
  DoCheck,
  OnDestroy,
  OnInit
} from '@angular/core';
import { Subject } from 'rxjs';
import { takeUntil } from 'rxjs/operators';
import { ItoDoItem, ToDoListService } from './to-do-list.service';

@Component({
  selector: 'app-to-do-list',
  templateUrl: './to-do-list.component.html',
  styleUrls: ['./to-do-list.component.css'],
})
export class ToDoListComponent implements OnInit, OnDestroy, DoCheck {
  toDoList: ItoDoItem[] = [];
  destroy$: Subject<boolean> = new Subject<boolean>();
  toDoListMapped: string[] = [];

  constructor(private toDoListService: ToDoListService) {}

  ngOnInit() {
    console.log('ngOnInit');

    //retrieve data from API
    this.toDoListService.getToDoList();

    //subscribe to object change
    this.toDoListService.toDoList
      .pipe(takeUntil(this.destroy$))
      .subscribe((data) => {
        this.toDoList = data;
      });
  }

  ngDoCheck() {
    console.log('ngDoCheck');

    this.toDoListMapped = this.toDoList.map(
      (toDoItem) => toDoItem.name + ' ==> ' + toDoItem.description
    );
  }

  removeItem(index: number) {
    this.toDoListService.removeToDoItem(index);
  }

  ngOnDestroy() {
    this.destroy$.next(true);
    this.destroy$.unsubscribe();
  }
}

<div
  class="container"
  *ngFor="let item of toDoListMapped; let odd = odd; let even = even; let index= index"
>
  <div class="card">
    <div class="card-body" [ngClass]="{ 'bg-info': odd, 'bg-secondary': even }">
      <div class="row">
        <div class="col-md-10">{{ item }}</div>
        <div class="col-md-1">
          <button
            type="button"
            (click)="removeItem(index)"
            class="btn btn-danger"
          >
            Delete
          </button>
        </div>
      </div>
    </div>
  </div>
</div>

// react-to-do-list/src/components/ToDoList/index.tsx
import * as React from 'react';

export interface ItoDoItem {
  id: number;
  name: string;
  description: string;
}

const allToDo: ItoDoItem[] = [
  { id: 0, name: 'Yoga', description: 'Tomorow at noone' },
  { id: 1, name: 'Client Meet', description: 'Prepare furniture list' },
  { id: 2, name: 'Call Mom', description: '' },
  { id: 3, name: 'Shopping', description: 'Prepare shopping list' },
];

export const ToDoList: React.FC = () => {
  const [toDoList, setToDoList] = React.useState<ItoDoItem[]>([]);
  const [dataLoaded, setDataLoaded] = React.useState<boolean>(false);

  const getDataFromAPI = async () => {
    let timeoutId: NodeJS.Timeout;

    const toDoListFromAPI = await new Promise<ItoDoItem[]>((resolve) => {
      timeoutId = setTimeout(() => {
        resolve(allToDo);
      }, 2000);
    }).then((allToDo) => {
      clearTimeout(timeoutId);
      return allToDo;
    });

    setToDoList(toDoListFromAPI);
    setDataLoaded(true);
  };

  React.useEffect(() => {
    console.log('Effect');

    if (!dataLoaded) {
      console.log('Retrieve data');
      getDataFromAPI();
    }
  }, []);

  const mapToDoItem = (toDoItem: ItoDoItem) => {
    return toDoItem.name + ' ==> ' + toDoItem.description;
  };

  const onDelete = (index: number) => {
    const newToDoList = toDoList.filter((item, i) => index !== i);
    setToDoList(newToDoList);
  };

  return (
    <div className="container">
      {toDoList.map((item, key) => (
        <div className='card' key={key}>
          <div className={`card-body ${key % 2 ? 'bg-info' : 'bg-secondary'}`}>
            <div className='row'>
              <div className='col-md-10'>{mapToDoItem(item)}</div>
              <div className='col-md-1'>
                <button
                  type='button'
                  onClick={() => onDelete(key)}
                  className='btn btn-danger'
                >
                  Delete
                </button>
              </div>
            </div>
          </div>
        </div>
      ))}
    </div>
  );
};
