// angular-to-do-list/src/app/header/header.component.ts
import { Component, EventEmitter, OnInit, Output } from '@angular/core';

@Component({
  selector: 'app-header',
  templateUrl: './header.component.html',
  styleUrls: ['./header.component.css'],
})
export class HeaderComponent {
  constructor() {}

  @Output() toggleFooterEvt = new EventEmitter();

  toggleFooter() {
    this.toggleFooterEvt.emit();
  }
}

<div class="bgcolorgree jumbotron jumbotron-fluid">
  <div class="container row">
    <div class="col-md-8">
      <h1 class="display-4">TO DO LIST</h1>
    </div>
    <div class="col-md-4">
      <p>
        <button class="btn btn-primary" (click)="toggleFooter()">
          Toggle Footer
        </button>
      </p>
    </div>
  </div>
</div>

// react-to-do-list/src/components/Header/index.tsx
import { Component } from 'react';
import './styles.css';

interface IHeader {
  toggleFooter: () => void;
}

export default class Header extends Component<IHeader> {
  render() {
    return (
      <div className='bgcolorgree jumbotron jumbotron-fluid'>
        <div className='container row'>
          <div className='col-md-8'>
            <h1 className='display-4'>TO DO LIST</h1>
          </div>
          <div className='col-md-4'>
            <p>
              <button
                className='btn btn-primary'
                onClick={this.props.toggleFooter}
              >
                Toggle Footer
              </button>
            </p>
          </div>
        </div>
      </div>
    );
  }
}
